name: collaction_cms
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  go_router: ^6.2.0
  injectable: ^2.1.1
  firebase_auth: ^4.3.0
  get_it: ^7.2.0
  cloud_firestore: ^4.4.5
  intl: ^0.17.0
  bloc: ^8.1.0
  equatable: ^2.0.5
  firebase_core: ^2.8.0
  flutter_svg: ^2.0.4
  navigation_history_observer: ^1.1.0
  rive: ^0.10.3
  http: ^0.13.5
  mocktail: ^0.3.0
  json_annotation: ^4.7.0
  flutter_dotenv: ^5.0.2
  defer_pointer: ^0.0.2
  country_codes: ^2.2.0
  country_icons: ^2.0.2
  image_network: ^2.5.1
  tap_canvas: ^0.9.4
  flutter_dropzone: ^3.0.5
  dotted_border: ^2.0.0+3
  crop_your_image: 
    git:
      url: https://github.com/andre-tm-hui/crop_your_image
      ref: main
  bloc_test: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.1.0+1
  injectable_generator: ^2.1.5
  lint: ^2.0.1
  json_serializable: ^6.5.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - env
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/rubik/Rubik-Black.ttf
          weight: 900
        - asset: fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/rubik/Rubik-Light.ttf
          weight: 300
    - family: CollActionIcons
      fonts:
        - asset: fonts/icons/CollactionIcons.ttf
