// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdueRyS_Q9gu6dgsVYVkhoJMSdFXThMvU',
    appId: '1:164614571144:web:7eefc7875a3ee722618b3d',
    messagingSenderId: '164614571144',
    projectId: 'collaction-52ca9',
    authDomain: 'collaction-52ca9.firebaseapp.com',
    storageBucket: 'collaction-52ca9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9LC1t4cUajvEwgaMrUXvJD1kWB5jkmKI',
    appId: '1:164614571144:android:21ca0527175028bf618b3d',
    messagingSenderId: '164614571144',
    projectId: 'collaction-52ca9',
    storageBucket: 'collaction-52ca9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3TxE9dhWjSFWydHBZu_ERZ9Jq4ap3xpc',
    appId: '1:164614571144:ios:e0ea7dcc821166d8618b3d',
    messagingSenderId: '164614571144',
    projectId: 'collaction-52ca9',
    storageBucket: 'collaction-52ca9.appspot.com',
    androidClientId: '164614571144-03svdk987n61sb19ppmgr0grabl2rvgf.apps.googleusercontent.com',
    iosClientId: '164614571144-ehnb7v0out32chdd2863ghett30b63i9.apps.googleusercontent.com',
    iosBundleId: 'org.collaction.collactionAdmin',
  );
}
